### ISSUE TITLE
Missing closing </h1>

### ISSUE THREAD

**Issue by nathansmith** [bnb/no-boilerplate#2]
I noticed that there's a missing `</h1>` here.

https://github.com/cutenode/no-boilerplate/commit/7df850d68364621801f4dd5e9c28f905992dce62#diff-eacf331f0ffc35d4b482f1d15a887d3bR8

Keep up the great work!

😎

**Comment by bnb** [comment]
Fixed in 8f3409a6c24e64ebeaa4ddcf9d9c7615569a1f63. Thank you! 🙏
